name: 'm ensure-poetry'
description: 'ensure that poetry is installed and cache the venv'
inputs:
  python-version:
    description: specify major and minor version of python
    default: 3.11
    required: false
  poetry-version:
    description: poetry version to install
    default: latest
    required: false
  venv-base-path:
    description: basepath for the venv
    default: /opt/venv
    required: false
  venv-name:
    description: name of the venv
    default: workspace
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup venv cache
      uses: actions/cache@v3
      with:
        path: /opt/venv
        # prettier-ignore
        key: ${{ runner.os }}-${{ inputs.python-version }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.python-version }}-venv-

    - name: ensure poetry
      id: venv-cache
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/ensure-poetry.sh ${{ inputs.poetry-version }} ${{ inputs.venv-base-path }} ${{ inputs.venv-name }} ${{ inputs.python-version }}
